#!/usr/bin/env node
// Usage: node scripts/tokens.mjs [--check]
// Generates design/tokens.css from design/tokens.json, the unchanged export of the design system
// "CV Creator" (Granat). The design system is the design source; the repo follows it
// (docs/brief.md). `--check` exits with 1 when design/tokens.css is not the generated file.
//
// What the generator adds to the export:
// - Screen sizes as clamp() from 375 to 1440 px. tokens.json holds the desktop value in
//   `fontSize` and the fluid value in the style's `usage` (see HANDOFF.md); the clamp must end
//   at the desktop value.
// - Granat light (default), Granat dark in two scopes (system setting, unless the page forces
//   light; and forced dark), dark on screen only. The other themes are sheet colours for print,
//   PDF (D5): `data-sheet="<theme>"` on the root element, inside the print block.
// - Print sizes as --print-* (the print styles use them) and a few repo tokens the design system
//   has no token for.

import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
export const TOKENS_JSON = join(root, 'design/tokens.json');
export const TOKENS_CSS = join(root, 'design/tokens.css');

// Tokens of the repo that the design system names as rules but not as tokens.
const REPO = {
  '--touch-target-min': '44px',
  '--duration-fast': '120ms',
  '--duration-base': '220ms',
  '--easing-standard': 'cubic-bezier(0.22, 0.61, 0.36, 1)',
};

const num = (v) => String(v).replace(/(\d)\.0(?=[a-z%]|$)/g, '$1');
const ref = (v) => (typeof v === 'string' && /^\{[a-z0-9-]+\}$/.test(v) ? `var(--${v.slice(1, -1)})` : v);
const decls = (entries, indent = '  ') => entries.map(([name, value]) => `${indent}${name}: ${value};`).join('\n');

// Screen value of a type style: the clamp() from its usage, or the fixed size.
function screenSize(style) {
  const token = style.name.replace(/^screen-/, '');
  const m = style.usage.match(new RegExp(`--font-size-${token}: (clamp\\([^)]*\\)|[\\d.]+rem)`));
  if (!m) throw new Error(`${style.name}: no --font-size-${token} in its usage`);
  const value = num(m[1]);
  const max = value.startsWith('clamp(') ? value.slice(0, -1).split(',').pop().trim() : value;
  if (max !== num(style.fontSize)) throw new Error(`${style.name}: ${value} does not end at ${style.fontSize}`);
  return value;
}

export function renderTokens(json) {
  if (json.version !== 3) throw new Error(`tokens.json version ${json.version}: the generator knows version 3`);
  const colors = json.color.tokens;
  const themeValues = (theme, { only } = {}) =>
    colors
      .filter((t) => t.value[theme] !== undefined && (!only || t.name.startsWith(only)))
      .map((t) => [`--${t.name}`, ref(t.value[theme])]);
  const groups = Object.fromEntries(json.type.groups.map((g) => [g.name.split(' · ')[0], g]));
  const screen = groups.Bildschirm.styles;
  const print = groups.Druck.styles;
  const families = Object.entries(json.type.families).map(([id, value]) => [`--font-${id}`, value]);
  const spacing = json.spacing.tokens.map((t) => [`--${t.name}`, t.usage.match(/clamp\([^)]*\)/)?.[0] ?? t.value]);
  const shadows = (theme) => json.shadow.tokens.map((t) => [`--${t.name}`, t.value[theme]]);
  const sheets = json.color.themes.map((t) => t.id).filter((id) => id !== 'light' && id !== 'dark');
  const dark = [...themeValues('dark'), ...shadows('dark')];

  return `/* Generated by scripts/tokens.mjs from design/tokens.json (design system "${json.name}",
   version ${json.version}). Do not edit: change tokens.json through a new export, then run
   \`npm run tokens\`. Theme "light" is Granat Papier, "dark" Granat Abend (screen only). */
:root {
  color-scheme: light;

  /* Colour: Granat Papier */
${decls([...themeValues('light'), ...shadows('light')])}

  /* Type: one family in Regular 400 (F2: Instrument Sans); the other nine are variants */
${decls(families)}
${decls(screen.map((s) => [`--font-size-${s.name.replace(/^screen-/, '')}`, screenSize(s)]))}
  --font-size-target: var(--font-size-subtitle);
  --font-size-headline: var(--font-size-subtitle);
${decls(screen.map((s) => [`--line-height-${s.name.replace(/^screen-/, '')}`, num(s.lineHeight)]))}

  /* Print sizes (pt in the export's px: 32px = 24pt) */
${decls(print.map((s) => [`--${s.name.replace(/^print-/, 'print-font-size-')}`, num(s.fontSize)]))}
${decls(print.map((s) => [`--${s.name.replace(/^print-/, 'print-line-height-')}`, num(s.lineHeight)]))}

  /* Space, radius, opacity */
${decls(spacing)}
${decls(json.radius.tokens.map((t) => [`--${t.name}`, t.value]))}
${decls(json.opacity.tokens.map((t) => [`--${t.name}`, t.value]))}

  /* Repo tokens without a design-system token */
${decls(Object.entries(REPO))}

}

/* Granat Abend: follows the system setting unless the page forces light. Screen only: print
   uses the sheet colours. */
@media screen and (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    color-scheme: dark;
${decls(dark, '    ')}
  }
}

/* Granat Abend, forced */
:root[data-theme="dark"] {
  color-scheme: dark;
${decls(dark)}
}

@media (prefers-reduced-motion: reduce) {
  :root {
    --duration-fast: 0ms;
    --duration-base: 0ms;
  }
}

/* Sheet colours of a version (print, PDF and paper view; the screen stays Granat, D5) */
@media print {
${sheets
  .map((id) => `  :root[data-sheet="${id}"] {\n${decls(themeValues(id, { only: 'color-' }), '    ')}\n  }`)
  .join('\n\n')}
}
`;
}

export async function generate() {
  return renderTokens(JSON.parse(await readFile(TOKENS_JSON, 'utf8')));
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const css = await generate();
  if (process.argv.includes('--check')) {
    const current = await readFile(TOKENS_CSS, 'utf8').catch(() => '');
    if (current !== css) {
      console.error('design/tokens.css is not generated from design/tokens.json: run npm run tokens');
      process.exit(1);
    }
    console.log('design/tokens.css matches design/tokens.json');
  } else {
    await writeFile(TOKENS_CSS, css);
    console.log('design/tokens.css written');
  }
}
